[project]
name = "velox"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Light", email = "lightdiamonds401@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "aiosqlite>=0.22.1",
    "fastapi>=0.143.0",
    "fastapi-users[sqlalchemy]>=15.0.5",
    "imagekitio>=5.10.0",
    "python-dotenv>=1.2.4",
    "uvicorn[standard]>=0.54.0",
]

[project.scripts]
velox = "velox:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"
